trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

steps:

# Run bash script
- bash: |
   find / -type f -name mvn 2>/dev/null
   echo "====> TEMP ${TMPDIR} <======"
  displayName: 'Test'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
